# What are ufuncs?

ufuncs stands for "Universal Functions" and they are NumPy functions that operate on the ndarray object.

# Why use ufuncs?

ufuncs are used to implement vectorization in NumPy which is way faster than iterating over elements.

They also provide broadcasting and additional methods like reduce, accumulate etc. that are very helpful for computation.

ufuncs also take additional arguments like:

where - boolean array or condition defining where the operations should take place.
dtype - defining the return type of elements
out - output array where the return value should be copied

# What is Vectorization?

Converting iterative statements into a vector based operation is called vectorization.

It is faster as modern CPUs are optimized for such operations.

# Add the Elements of Two Lists

list 1 : [1, 2, 3, 4]
list 2 : [4, 5, 6, 7]

One way of doing it is to iterate over both of the lists and then sum each element.

In [1]:
# Without ufunc, we can use the zip() method

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
    z.append(i + j)
print(z)

[5, 7, 9, 11]


NumPy has a ufunc for this, called add(x, y) that will produce the same result.

In [2]:
import numpy as np

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)

[ 5  7  9 11]


# How to Create Your Own ufunc?

To create your own ufunc, you have to define a function, like you do with normal functions in Python, then you add it to your NumPy ufunc library with the frompyfunc() method.

The frompyfunc() method takes the following arguments:

1. function - the name of the function.
2. inputs - the number of input arguments (arrays).
3. output - the number of output arrays.

In [4]:
# Create your own ufunc for addition

def myadd(x, y):
    return x + y

myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

[6 8 10 12]


# Check if a Function is a ufunc

Check the type of a function to check if it is a ufunc or not.

A ufunc should return <class 'numpy.ufunc'>

In [5]:
print(type(np.add))

<class 'numpy.ufunc'>


# Simple Arithmetic

You could use arithmetic operations +, -, *, / directly between NumPy arrays, but this section discusses an extension of the same where we have functions that can take any array-like objects e.g. lists, tuples, etc. and perform arithmetic conditionally.

Arithmetic Conditionally: means that we can define conditions where the arithmetic condition should happen.

All of the discussed arithmetic functions take a where parameter in which we can specify that condition.

# Addition

The add() function sums the content of two arrays, and returns the results in a new array.

In [6]:
# Add the values in arr1 to the values in arr2

arr1 = np.array([10, 11, 12, 13, 14, 15])

arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)

print(newarr)

[30 32 34 36 38 40]


# Subtraction

The subtract() function subtracts the values from one array with the values from another array, and return the results in a new array.

In [8]:
arr1 = np.array([10, 20, 30, 40, 50, 60])

arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)

print(newarr)

[-10  -1   8  17  26  35]


# Multiplication

The multiply() function multiplies the values from one array with the values from another array, and returns the results in a new array.

In [9]:
newarr = np.multiply(arr1, arr2)

print(newarr)

[ 200  420  660  920 1200 1500]


# Division

The divide() function divides the values from one array with the values from another array, and returns the results in a new array.

In [10]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 4, 10, 8, 2, 33])

newarr = np.divide(arr1, arr2)
print(newarr)

[ 3.33333333  5.          3.          5.         25.          1.81818182]


# Power

The power() function raises the values from the first array to the power of the values of the second array, and return the results in a new array.

In [3]:
# Raise the values in arr1 to the power of values in arr2

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

newarr = np.power(arr1, arr2)

print(newarr)

[         1000       3200000     729000000 6553600000000          2500
             0]


# Remainder

Both mod() and the remainder() functions return the remainder of the values in the first array corresponding to the values in the second array, and return the results in a new array.

In [5]:
# Return the remainders

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)

print(newarr)

[ 1  6  3  0  0 27]


You get the same result with the remainder function.

# Quotient and Mod

The divmod() function return both the quotient and the mod. The return value is two arrays, the first array contains the quotient and the second contains the mod.

In [6]:
newarr = np.divmod(arr1, arr2)

print(newarr)

(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))


# Absolute Values

Both the absolute() and the abs() functions do the same absolute operation element-wise but we should use absolute() to avoid confusion with python's inbuilt math.abs()

In [7]:
arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)

print(newarr)

[1 2 1 2 3 4]


# Truncation

Remove the decimals, and return the float number closest to zero. Use the trunc() and fix() functions.

In [9]:
arr = np.fix([-3.1666, 3.6667])

print(arr)

[-3.  3.]


# Rounding

The around() function increments preceding digit or decimal by 1 if >= 5 else do nothing.

In [10]:
arr = np.around(3.1666, 2)
print(arr)

3.17


# Log at Base 2

Use the log2() function to perform log at the base 2.

In [12]:
arr = np.arange(1, 10)

print(np.log2(arr))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


# Log at Base 10

Use the log10() function to perform log at the base 10.

In [13]:
arr = np.arange(1, 10)

print(np.log10(arr))

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


# Natural Log

Use the log() function to perform log at the base e.

In [14]:
arr = np.arange(1, 10)

print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


# Log at Any Base

Numpy does not provide any function to take log at any base, so we can use the frompyfunc() function along with inbuilt function math.log() with two input parameters and one output parameter.

In [15]:
from math import log

nplog = np.frompyfunc(log, 2, 1)

print(nplog(100, 15))

1.7005483074552052


# Summations

What is the difference between summation and addition?

Addition is done between two arguments whereas summation happens over n elements.

In [16]:
# Add the values in arr1 to the values in arr2

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.add(arr1, arr2)

print(newarr)

[2 4 6]


In [17]:
# Sum the values in arr1 and the values in arr2

newarr = np.sum([arr1, arr2])

print(newarr)

12


# Summation Over an Axis

If you specify axis=1, NumPy will sum the numbers in each array.

In [18]:
# Perform summation in the following array over 1st axis

newarr = np.sum([arr1, arr2], axis=1)

print(newarr)

[6 6]


# Cummulative Sum

Cummulative sum means partially adding the elements in array.

E.g. The partial sum of [1, 2, 3, 4] would be [1, 1+2, 1+2+3, 1+2+3+4]

Perform partial sum with the sumsum() function.

In [19]:
arr = np.array([1, 2, 3])

newarr = np.cumsum(arr)

print(newarr)

[1 3 6]


# Products

To find the product of the elements in an array, use the prod() function.

In [20]:
x = np.prod(arr)

print(x)

6


In [21]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

x = np.prod([arr1, arr2])

print(x)

40320


# Product Over an Axis

If you specify axis=1, NumPy will return the product of each array.

In [22]:
newarr = np.prod([arr1, arr2], axis=1)

print(newarr)

[  24 1680]


# Cummulative Product

Perform partial product with the cumprod() function.

In [24]:
arr = np.array([5, 6, 7, 8])

newarr = np.cumprod(arr)

print(newarr)

[   5   30  210 1680]
