# Practice

- Create a 5x5 NumPy array with random integers between 10 - 99

In [25]:
import numpy as np

arr = np.random.randint(10, 99, size=(5, 5))
print(arr)

[[43 73 91 25 10]
 [73 74 76 79 56]
 [56 13 79 77 66]
 [28 15 95 47 24]
 [90 44 66 45 98]]


- Compute row-wise and column-wise sums

In [28]:
count = 1
col1, col2, col3, col4, col5 = 0, 0, 0, 0, 0
for i in arr:
    print(f"Row {count} sum: {sum(i)}")
    col1 += i[0]
    col2 += i[1]
    col3 += i[2]
    col4 += i[3]
    col5 += i[4]
    count += 1
print(f"Column 1 sum: {col1}")
print(f"Column 2 sum: {col2}")
print(f"Column 3 sum: {col3}")
print(f"Column 4 sum: {col4}")
print(f"Column 5 sum: {col5}")


Row 1 sum: 242
Row 2 sum: 358
Row 3 sum: 291
Row 4 sum: 209
Row 5 sum: 343
Column 1 sum: 290
Column 2 sum: 219
Column 3 sum: 407
Column 4 sum: 273
Column 5 sum: 254
